function authCard(title, body) { return `<div class="min-h-screen bg-slate-50 px-4 py-10"><main class="mx-auto max-w-md rounded-3xl border bg-white p-7 shadow-sm"><h1 class="text-2xl font-bold">${title}</h1>${body}<p class="mt-5 text-center text-sm"><a href="#/login" class="font-semibold text-blue-700">กลับหน้าเข้าสู่ระบบ</a></p></main></div>`; }
function renderForgotPasswordView(app) {
  app.innerHTML = authCard('ลืมรหัสผ่าน', `<p class="mt-2 text-sm text-slate-500">กรอกอีเมลที่ใช้สมัคร ลิงก์มีอายุ 30 นาที</p><form id="forgotForm" class="mt-5 space-y-4"><input name="email" type="email" required placeholder="name@example.com" class="w-full rounded-xl border px-4 py-3"><button class="w-full rounded-xl bg-slate-900 px-4 py-3 font-semibold text-white">ขอลิงก์รีเซ็ต</button></form><div id="forgotResult" class="mt-4 hidden rounded-xl bg-blue-50 p-3 text-sm text-blue-800"></div>`);
  document.getElementById('forgotForm').onsubmit = async event => { event.preventDefault(); try { const data = await api('/auth/forgot-password', { method:'POST', body:JSON.stringify(Object.fromEntries(new FormData(event.target))) }); const box = document.getElementById('forgotResult'); box.classList.remove('hidden'); box.innerHTML = `${escapeHtml(data.message)}${data.reset_token ? `<br><a class="mt-2 inline-block font-bold underline" href="#/reset-password?token=${encodeURIComponent(data.reset_token)}">เปิดหน้าเปลี่ยนรหัสผ่าน (Development)</a>` : ''}`; } catch (error) { appToast(error.message, 'error'); } };
}
function renderResetPasswordView(app, token) {
  app.innerHTML = authCard('ตั้งรหัสผ่านใหม่', `<form id="resetForm" class="mt-5 space-y-4"><input name="password" type="password" minlength="6" maxlength="21" required placeholder="รหัสผ่านใหม่ 6-21 ตัวอักษร" class="w-full rounded-xl border px-4 py-3"><input name="confirm_password" type="password" minlength="6" maxlength="21" required placeholder="ยืนยันรหัสผ่านใหม่" class="w-full rounded-xl border px-4 py-3"><button class="w-full rounded-xl bg-teal-700 px-4 py-3 font-semibold text-white">บันทึกรหัสผ่านใหม่</button></form>`);
  document.getElementById('resetForm').onsubmit = async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); if (data.password !== data.confirm_password) return appToast('รหัสผ่านทั้งสองช่องไม่ตรงกัน', 'error'); try { const result = await api('/auth/reset-password', { method:'POST', body:JSON.stringify({ token, password:data.password }) }); appToast(result.message); location.hash = '#/login'; } catch (error) { appToast(error.message, 'error'); } };
}
window.renderForgotPasswordView = renderForgotPasswordView; window.renderResetPasswordView = renderResetPasswordView;
