function publicCatalogCard(item) {
  const image = item.files?.[0]?.file_url;
  return `<a href="item.html?id=${encodeURIComponent(item.asset_code)}" class="group overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div class="aspect-[4/3] bg-slate-100">${image ? `<img src="${absUrl(image)}" alt="${escapeHtml(item.name)}" loading="lazy" class="h-full w-full object-contain">` : '<div class="flex h-full items-center justify-center text-5xl">🔬</div>'}</div><div class="p-4"><p class="font-mono text-xs font-bold text-teal-700">${escapeHtml(item.asset_code)}</p><h3 class="mt-1 font-bold text-slate-950">${escapeHtml(item.name)}</h3><p class="mt-1 text-sm text-slate-500">${escapeHtml(item.category?.name || 'ไม่ระบุหมวดหมู่')} · ${escapeHtml(item.status?.name || '-')}</p></div></a>`;
}
function renderPublicCatalog(app, payload = null) {
  const data = payload?.data || {items:[],categories:[]}; const filters = payload?.meta?.filters || {};
  app.innerHTML = `<div class="min-h-screen bg-slate-50"><header class="border-b bg-white"><nav class="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4"><a href="#/" class="text-lg font-black text-teal-800">Lab QR Asset</a><div class="flex gap-2"><a href="#/login" class="rounded-xl border px-4 py-2 text-sm font-semibold">เข้าสู่ระบบ</a><a href="#/register" class="rounded-xl bg-teal-700 px-4 py-2 text-sm font-semibold text-white">สมัครสมาชิก</a></div></nav></header><section class="bg-gradient-to-br from-slate-950 via-teal-950 to-teal-800 px-4 py-16 text-white"><div class="mx-auto max-w-5xl text-center"><p class="font-semibold text-teal-200">ระบบจัดการอุปกรณ์ห้องปฏิบัติการ</p><h1 class="mt-3 text-4xl font-black sm:text-6xl">ค้นหาอุปกรณ์ได้จากทุกที่</h1><p class="mx-auto mt-4 max-w-2xl text-slate-200">ดูข้อมูล สถานะ หมวดหมู่ และเอกสารสาธารณะของอุปกรณ์ผ่าน QR Code</p></div></section><main class="mx-auto max-w-7xl px-4 py-8"><form id="catalogForm" class="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-4"><input name="search" maxlength="100" value="${escapeHtml(filters.search || '')}" placeholder="ค้นหารหัส ชื่อ หรือรุ่น" class="rounded-xl border px-4 py-3 md:col-span-2"><select name="category_id" class="rounded-xl border px-4 py-3"><option value="">ทุกหมวดหมู่</option>${data.categories.map(x => `<option value="${x.id}" ${Number(filters.category_id) === x.id ? 'selected' : ''}>${escapeHtml(x.name)}</option>`).join('')}</select><select name="sort" class="rounded-xl border px-4 py-3"><option value="code-asc">รหัส A-Z</option><option value="code-desc" ${filters.sort==='code-desc'?'selected':''}>รหัส Z-A</option><option value="name-asc" ${filters.sort==='name-asc'?'selected':''}>ชื่อ A-Z</option><option value="name-desc" ${filters.sort==='name-desc'?'selected':''}>ชื่อ Z-A</option><option value="updated-desc" ${filters.sort==='updated-desc'?'selected':''}>อัปเดตล่าสุด</option></select><button class="rounded-xl bg-slate-900 px-4 py-3 font-semibold text-white md:col-span-4">ค้นหาและกรอง</button></form><div class="mt-8 flex items-center justify-between"><h2 class="text-2xl font-bold">รายการอุปกรณ์</h2><span class="text-sm text-slate-500">${payload?.meta?.count || 0} รายการ</span></div><section class="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">${data.items.length ? data.items.map(publicCatalogCard).join('') : '<p class="rounded-2xl border bg-white p-10 text-center text-slate-500 sm:col-span-2 lg:col-span-3 xl:col-span-4">ไม่พบอุปกรณ์ตามเงื่อนไข</p>'}</section></main></div>`;
  document.getElementById('catalogForm').onsubmit = async event => { event.preventDefault(); const query = new URLSearchParams(new FormData(event.target)); [...query.entries()].forEach(([k,v]) => !v && query.delete(k)); try { renderPublicCatalog(app, await api(`/public/catalog?${query}`)); } catch (error) { appToast(error.message,'error'); } };
}
async function loadPublicCatalog(app) { app.innerHTML = '<div class="p-10 text-center">กำลังโหลดรายการอุปกรณ์...</div>'; renderPublicCatalog(app, await api('/public/catalog')); }
window.loadPublicCatalog = loadPublicCatalog;
